/:
  controller: Controllers\default
  action: default

/test/yves:
  controller: Conrollers\default
  action: default

/ajout-utilisateur:
  controller: Controllers\user
  action: "add"

/utilisateur:
  controller: Controllers\user
  action: "default"

/se-connecter:
  controller: Controllers\user
  action: "login"

/s-inscrire:
  controller: Controllers\user
  action: "register"

/mot-de-passe-oublie:
  controller: Controllers\user
  action: "forgotPwd"


/tableau-de-bord:
  controller: "user"
  action: "dashboardBack"

/pages:
  controller: "user"
  action: "allPage"

/cours:
  controller: "user"
  action: "cours"

/apparence:
  controller: "user"
  action: "apparence"

/utilisateur:
  controller: "user"
  action: "default"

/categories:
  controller: "user"
  action: "categories"

/tradeline:
  controller: "user"
  action: "tradeLine"
