/:
  controller: Controllers\default
  action: default

/test/yves:
  controller: Conrollers\default
  action: default

/ajout-utilisateur:
  controller: Controllers\user
  action: "add"

/utilisateur:
  controller: Controllers\user
  action: "default"

/se-connecter:
  controller: Controllers\user
  action: "login"

/s-inscrire:
  controller: Controllers\user
  action: "register"

/mot-de-passe-oublie:
  controller: Controllers\user
  action: "forgotPwd"

/dashboard:
  controller: Controllers\user
  action: "dashboardBack"

/all-page:
  controller: Controllers\user
  action: "allPage"